### PR TITLE
don't complain about no changed when for upgrade command

### PR DESCRIPTION
**Pull request by evgeni**
it's in a sensible block

### CODE REVIEW

**Comment by evgeni** [comment]
well, at least that role fails later now :woman_shrugging:

**Comment by evgeni** [comment]
with all those changes, the remaining failing role is… postgresql_upgrade

it fails because it needs to install foreman 2.3 but 2.3 can't be (by default) deployed on CentOS8 stream as the used PostgreSQL puppet module doesn't recognize it :(

**Comment by ehelms** [comment]
Originally we wanted to use an installer run to feel more confident about an upgrade with "real" data. Older Foreman versions will start to wane as this indicates so I'd be in favor of dropping the installer part of the postgresql upgrade role and simplifying the testing.

**Comment by evgeni** [comment]
> Originally we wanted to use an installer run to feel more confident about an upgrade with "real" data. Older Foreman versions will start to wane as this indicates so I'd be in favor of dropping the installer part of the postgresql upgrade role and simplifying the testing.

So, like this? Setup a 10, upgrade to 12?

**Comment by evgeni** [comment]
:green_apple:

**Review by ehelms — APPROVED** [review]

**Pull request merged**
