### PR TITLE
Bump version to 1.0.0

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
There is no commit with 1.0.0 as the version?

**Comment by ehelms** [comment]
> There is no commit with 1.0.0 as the version?

Huh?

**Comment by evgeni** [comment]
This PR bumps the version to `1.0.0-dev` and there is no intermediate commit to bump it to `1.0.0` so there is nothing to release.

Or this *preparation* for a 1.0.0, but not the 1.0.0 yet?

**Comment by ehelms** [comment]
I was thinking to prep, fix CI, grab a few of the open PRs and then do a release release.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
